//tag::ref-doc[]
= gRPC Processor

This processor uses gRPC to process Messages via a remote process written in any language that supports gRPC. This
pattern, allows the Java app to handle the stream processing while the gRPC service handles the business logic.
The service must implement the link:https://grpc.io/[grpc] service using link:.
./grpc-app-protos/src/main/proto/processor.proto[this protobuf schema].

[NOTE]
====
The gRPC client stub is blocking by default. Asynchronous and streaming stubs are provided. The Asynchronous stub will
perform better if the server is multi-threaded however message ordering will not be guaranteed. If the server
supports bidirectional streaming, use the streaming stub.
====

[NOTE]
====
A `riff` stub is available for interoperability with https://projectriff.io/[riff] function containers. This does not
 interact with the Riff FaaS platform but supports running an existing function container standalone, for example,
 `docker run -it -p10382:10382 some/riff-function:latest` .
====


== Input

=== Headers
Headers are available to the sidecar application via the link:../grpc-app-protos/src/main/proto/process.proto[process]
schema if `grpc.include-headers` is `true`. The header value contains one or more string values to support multiple
values, e.g., the HTTP `Accepts` header.

=== Payload
The payload is a byte array as defined by the link:../grpc-app-protos/src/main/proto/process.proto[schema].

== Output

=== Headers
In most cases the return message should simply contain the original headers provided.
The sidecar application may modify or add headers however it is recommended to only add headers if necessary.

=== Payload
It is expected that the payload will normally be a string or byte array. However common primitive types are supported
 as defined by the link:../grpc-app-protos/src/main/proto/message.proto[schema].

== Options

The **$$grpc$$** $$processor$$ has the following options:

//tag::configuration-properties[]
$$grpc.host$$:: $$The gRPC host name.$$ *($$String$$, default: `$$<none>$$`)*
$$grpc.idle-timeout$$:: $$The idle timeout in seconds.$$ *($$Long$$, default: `$$0$$`)*
$$grpc.include-headers$$:: $$Flag to include headers in Messages to the remote process.$$ *($$Boolean$$, default: `$$false$$`)*
$$grpc.max-message-size$$:: $$The maximum message size (bytes).$$ *($$Integer$$, default: `$$0$$`)*
$$grpc.plain-text$$:: $$Flag to send messages in plain text. SSL configuration required otherwise.$$ *($$Boolean$$, default: `$$true$$`)*
$$grpc.port$$:: $$The gRPC server port.$$ *($$Integer$$, default: `$$0$$`)*
$$grpc.stub$$:: $$RPC communications style (default 'blocking').$$ *($$Stub$$, default: `$$<none>$$`, possible values: `async`,`blocking`,`streaming`,`riff`)*
//end::configuration-properties[]

//end::ref-doc[]
== Build

```
$> mvn package
```

== Example

```
$java -jar grpc-processor.jar --grpc.host=somehost --grpc.port=1234
```
